project_id = "gjzhntrcogbamirtudsp"

[functions.create-pix]
verify_jwt = false

[functions.pepper-webhook]
verify_jwt = false

[functions.pixup-webhook]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-transactions]
verify_jwt = false

[functions.toggle-access]
verify_jwt = false

[functions.check-access]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.update-email]
verify_jwt = false

[functions.save-license]
verify_jwt = false

[functions.admin-settings]
verify_jwt = false

[functions.validate-license]
verify_jwt = false
